name: Build and Deploy to Azure

on:
  push:
    branches:
      - develop
      - main

permissions:
  id-token: write
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Create .env file
        run: |
          touch frontend/.env
          echo "VITE_APP_MODE=${{ vars.VITE_APP_MODE }}" >> frontend/.env

      - name: Run key generation script
        run: |
          chmod +x ./backend/generate-keys.sh
          ./backend/generate-keys.sh

      - name: Build with Maven
        run: mvn clean package

      - name: Build Docker image
        run: |
          docker build . -t pro-a
          docker tag pro-a ${{ secrets.AZURE_ACR_NAME }}.azurecr.io/pro-a:${{ github.ref_name == 'main' && 'prod' || 'dev' }}

      - name: Log in to Azure Container Registry
        uses: azure/docker-login@v1
        with:
          login-server: ${{ secrets.AZURE_ACR_NAME }}.azurecr.io
          username: ${{ secrets.AZURE_ACR_USERNAME }}
          password: ${{ secrets.AZURE_ACR_PASSWORD }}

      - name: Push Docker image to ACR
        run: |
          docker push ${{ secrets.AZURE_ACR_NAME }}.azurecr.io/pro-a:${{ github.ref_name == 'main' && 'prod' || 'dev' }}

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Azure login
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v2
        with:
          app-name: ${{ github.ref_name == 'main' && secrets.AZURE_WEB_APP_NAME_PROD || secrets.AZURE_WEB_APP_NAME_DEV }}
          images: |
            ${{ secrets.AZURE_ACR_NAME }}.azurecr.io/pro-a:${{ github.ref_name == 'main' && 'prod' || 'dev' }}
