name: Release Version

on:
  workflow_dispatch:
    inputs:
      releaseVersion:
        description: the release version
        required: true
        type: String
      developmentVersion:
        description: the next dev iteration version
        required: true
        type: String
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '21'
          cache: 'maven'
      - name: Configure Git User
        run: |
          git config user.email "actions@github.com"
          git config user.name "ReleaseAction[bot]"
      - name: Release
        run: ./mvnw -B release:clean release:prepare -DreleaseVersion=$RELEASE_VERSION -DdevelopmentVersion=$DEV_VERSION
        env:
          RELEASE_VERSION: ${{ github.event.inputs.releaseVersion }}
          DEV_VERSION: ${{ github.event.inputs.developmentVersion }}
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: ${{format('v{0}',  github.event.inputs.releaseVersion) }}
      - name: Build
        run: |
           ./mvnw clean package
           mkdir ./tmp
           sudo cp -r /home/runner/work/ProA/ProA/backend/target/ /tmp
           sudo chown -R runner:runner /tmp
      - name: Upload files
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{format('v{0}',  github.event.inputs.releaseVersion) }}
          files: /tmp/*/pro-a-*.jar